### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by ghost** [Xenophilicy/MaxEnchants#1]
Maybe have an option in the config saying if you want it to broadcast True Or False

**Comment by Xenophilicy** [comment]
Alright, sounds good. @SuperiorOP2YT are you wanting this broadcast to resemble the vanilla one or the one I have added? I can always make it custom too if you'd like even more customization.

**Comment by ghost** [comment]
sorry for late response i usually answer fast. i suggest like configuration to broadcasting messages to true or false for when enchantments occur and if possible up to you maybe configuration of the message when someone enchants their weapons. And thats about it i have no other suggestion since this plugin is 100/10 amazing

**Comment by Xenophilicy** [comment]
@SuperiorOP2YT Added in version 1.1.0, check it out on Poggit [here](https://poggit.pmmp.io/p/MaxEnchants/1.1.0)!

**Comment by TarzaxDev** [comment]
Hello, a friend blew up tnt on my world with multi world and as soon as I go over it the server closes . Help me please
