### ISSUE TITLE
In my own plugin I want to add a one hit sword using your plugin how can I do that

### ISSUE THREAD

**Issue by ghost** [Xenophilicy/MaxEnchants#10]

**Comment by Xenophilicy** [comment]
Put a high level of sharpness on the sword you want to use as a "one hit sword".

**Comment by ghost** [comment]
What I mean is what code can I add using your plugin to make this sword one hit. Because I’m working on a murder mystery plugin.

foreach($playersArena as $pl)
                                                                        {
                                                                        	if(strpos($pl->getNameTag(), "§b") !== false)
                                                                        {
                                                                        	$item = Item::get(Item::DIAMOND_SWORD, 0, 1);
                $item = Item::get(Item::DIAMOND_SWORD, 0, 1);
                $pl->setNameTag("§b");
                $pl->getInventory()->setItem(1, $item);
                $pl->getInventory()->setItem(0, Item::get(Item::BREAD, 0, 1));
                $pl->getInventory()->setItem(2, Item::get(Item::CLOCK, 0, 1));
                $pl->addTitle("§cYOU ARE THE MURDERER");
                }
                }
                }

**Comment by Xenophilicy** [comment]
You don't need to use my plugin to do that, just use `Item::addEnchantment()` like so:
```php
foreach($playersArena as $pl){
    if(strpos($pl->getNameTag(), "§b") !== false){
        $item = Item::get(Item::DIAMOND_SWORD, 0, 1);
        $item->addEnchantment(new EnchantmentInstance(Enchantment::getEnchantment(Enchantment::SHARPNESS), 32767));
        $pl->setNameTag("§b");
        $pl->getInventory()->setItem(1, $item);
        $pl->getInventory()->setItem(0, Item::get(Item::BREAD, 0, 1));
        $pl->getInventory()->setItem(2, Item::get(Item::CLOCK, 0, 1));
        $pl->addTitle("§cYOU ARE THE MURDERER");
    }
}
```

**Comment by ghost** [comment]
I done that before but I get a error. But lemme try this one
