### ISSUE TITLE
Awesome!

### ISSUE THREAD

**Issue by xAndrew52** [Xenophilicy/MaxEnchants#2]
i like all of your plugins. can you please make an ShopUI plugin with many items abd configurable from config? thanks.

- Andrei

**Comment by Xenophilicy** [comment]
Please don't request plugins in my issue section. I will not be making a public shop plugin because there are plenty already on Poggit to choose from. If you want more info and for future inquiries, please DM me on Discord `Xenophilicy#0001` instead of creating a useless issue.
