### ISSUE TITLE
Fix console enchantment

### ISSUE THREAD

**Issue by Thunder33345** [Xenophilicy/MaxEnchants#3]
If vanilla enchant, can be ran on console, to target a player, i dont see why this cant

**Comment by Xenophilicy** [comment]
Ah that was something I forgot to remove back when I was grabbing only the player's hand. I'll fix that in the next update. Thanks for reminding me 👍

**Comment by Xenophilicy** [comment]
@Thunder33345 I have fixed this in version 1.1.0, you can now execute the command from console. Check it out on Poggit [here](https://poggit.pmmp.io/p/MaxEnchants/1.1.0)!
