### ISSUE TITLE
Suggestion - Individual max levels & enchantment list in command/config

### ISSUE THREAD

**Issue by ApexPE** [Xenophilicy/MaxEnchants#4]
Add in the config a option like this:

# list enchant id and max level below
# Example EnchantID:MaxLevel
# list all you need
enchantmaxlevels:
15:5

And add a file in the resource file where all enchant names and I’d can be found

**Comment by Xenophilicy** [comment]
Are you wanting individual enchantment levels for chosen enchantment IDs? I love the second idea but I'd actually like to make an in-game command as well for listing available enchantments with their names and IDs. I can definitely add a list of available enchantment names in the config as well, no problem 👍

**Comment by Xenophilicy** [comment]
Enhancement was added in version 1.2.0 available [here](https://poggit.pmmp.io/p/MaxEnchants/1.2.0) on Poggit!
