### ISSUE TITLE
Suggestion...

### ISSUE THREAD

**Issue by siahfivem** [Xenophilicy/MaxEnchants#6]
Maybe add away to add onto a sign... like enchant sign with money to buy

**Comment by siahfivem** [comment]
Please & thank you.

**Comment by Xenophilicy** [comment]
You can already set up enchantment signs with another plugin. The point of my plugin is simply to change the enchant level. Please use another plugin to do this.

**Comment by SlowClubStudios** [comment]
What plugin would you recommend?

**Comment by SlowClubStudios** [comment]
> You can already set up enchantment signs with another plugin. The point of my plugin is simply to change the enchant level. Please use another plugin to do this.

Recommend?

**Comment by siahfivem** [comment]
> You can already set up enchantment signs with another plugin. The point of my plugin is simply to change the enchant level. Please use another plugin to do this.

what u Recommend?
